languageCode = "en-us"
title = "Timothy Quang Phuc Nguyen"
baseurl = "http://quangphuc789.github.io/"
theme = "dimension"

[params]
  title = "Timothy Quang Phuc Nguyen"
  description = 'A LIFE TRAVELLER'
  copyright = "quangphuc789"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UCDujncETm-8rhhHOXkGomNg"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/quangphuc.nguyen"

[[params.social]]
  medium = "quora"
  icon = "quora"
  link = "https://www.quora.com/profile/Timothy-Quang-Phuc-Nguyen"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/quangphuc789"
